### ISSUE TITLE
Failed building wheel for npyscreen

### ISSUE THREAD

**Issue by fansel** [FahrplanDatenGarten/FahrplanDatenGarten#5]
Huhu, 
kriege seit Installation der requirements im venv folgenden Log:

```
(.venv) felix@Felix:/home/FahrplanDatenGarten$ pip install -r requirements.txt
Collecting django (from -r requirements.txt (line 1))
...
Building wheels for collected packages: npyscreen
  Running setup.py bdist_wheel for npyscreen ... error
  Complete output from command /home/FahrplanDatenGarten/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-igyjk7h9/npyscreen/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpy6od4v08pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for npyscreen
  Running setup.py clean for npyscreen
Failed to build npyscreen
Installing collected packages: pytz, sqlparse, django, wheel, dj-database-url, certifi, urllib3, chardet, idna, requests, fdfgen, npyscreen, soupsieve, beautifulsoup4
Exception:
Traceback (most recent call last):
  File "/home/FahrplanDatenGarten/.venv/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/FahrplanDatenGarten/.venv/lib/python3.6/site-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/home/FahrplanDatenGarten/.venv/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/FahrplanDatenGarten/.venv/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/FahrplanDatenGarten/.venv/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/FahrplanDatenGarten/.venv/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/FahrplanDatenGarten/.venv/lib/python3.6/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/FahrplanDatenGarten/.venv/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Keine Berechtigung: '/home/FahrplanDatenGarten/.venv/lib/python3.6/site-packages/pytz-2019.3.dist-info'
`
```
Wenn ich aber `pip install -r requirements.txt` verwende erhalte ich nur folgende Fehler:

```
...
Building wheels for collected packages: npyscreen
  Running setup.py bdist_wheel for npyscreen ... error
  Complete output from command /home/FahrplanDatenGarten/.venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-13r0kvy3/npyscreen/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp1t032nilpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for npyscreen
  Running setup.py clean for npyscreen
Failed to build npyscreen
Installing collected packages: sqlparse, pytz, django, wheel, dj-database-url, idna, certifi, chardet, urllib3, requests, fdfgen, npyscreen, soupsieve, beautifulsoup4
  Running setup.py install for npyscreen ... done
Successfully installed beautifulsoup4-4.8.1 certifi-2019.9.11 chardet-3.0.4 dj-database-url-0.5.0 django-2.2.6 fdfgen-0.16.1 idna-2.8 npyscreen-4.10.5 pytz-2019.3 requests-2.22.0 soupsieve-1.9.4 sqlparse-0.3.0 urllib3-1.25.6 wheel-0.33.6
(.venv) felix@Felix:/home/FahrplanDatenGarten$  
`
```

**Comment by n0emis** [comment]
Moin Felix, 

du hast auf dem Rechner das Repository nicht in dein Home-Verzeichniss (wahrscheinlich `/home/felix/`) sondern in einen anderen Ordner geclonet. In diesem Ordner hast du aber keine Schreibrechte. Versuch das Repo einfach nochmal in deinen Benutzerordner zu laden, hier sollte das ganze dann funktionieren.

**Comment by fansel** [comment]
Jo! Nummer 1 ist gefixxed, danke dir, allerdings wird npyscreen immer noch nicht installiert ...
